name: CD

concurrency: 
  group: deploy-dev-front
  cancel-in-progress: true

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.READ_ALL_REPO_PAT }}
          submodules: recursive

      - name: Cache node modules
        uses: actions/cache@v3.0.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node_modules-
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://travely-dev-frontend-s3-bucket
          aws cloudfront create-invalidation --region ap-northeast-2 --distribution-id E3M1M02TPVD7DZ --paths "/*"
